package com.shidao.web.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ExporEvaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public ExporEvaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEeIdIsNull() {
            addCriterion("EE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEeIdIsNotNull() {
            addCriterion("EE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEeIdEqualTo(Long value) {
            addCriterion("EE_ID =", value, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdNotEqualTo(Long value) {
            addCriterion("EE_ID <>", value, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdGreaterThan(Long value) {
            addCriterion("EE_ID >", value, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("EE_ID >=", value, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdLessThan(Long value) {
            addCriterion("EE_ID <", value, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdLessThanOrEqualTo(Long value) {
            addCriterion("EE_ID <=", value, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdIn(List<Long> values) {
            addCriterion("EE_ID in", values, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdNotIn(List<Long> values) {
            addCriterion("EE_ID not in", values, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdBetween(Long value1, Long value2) {
            addCriterion("EE_ID between", value1, value2, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeIdNotBetween(Long value1, Long value2) {
            addCriterion("EE_ID not between", value1, value2, "eeId");
            return (Criteria) this;
        }

        public Criteria andEeDetailIsNull() {
            addCriterion("EE_DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andEeDetailIsNotNull() {
            addCriterion("EE_DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEeDetailEqualTo(String value) {
            addCriterion("EE_DETAIL =", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailNotEqualTo(String value) {
            addCriterion("EE_DETAIL <>", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailGreaterThan(String value) {
            addCriterion("EE_DETAIL >", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailGreaterThanOrEqualTo(String value) {
            addCriterion("EE_DETAIL >=", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailLessThan(String value) {
            addCriterion("EE_DETAIL <", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailLessThanOrEqualTo(String value) {
            addCriterion("EE_DETAIL <=", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailLike(String value) {
            addCriterion("EE_DETAIL like", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailNotLike(String value) {
            addCriterion("EE_DETAIL not like", value, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailIn(List<String> values) {
            addCriterion("EE_DETAIL in", values, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailNotIn(List<String> values) {
            addCriterion("EE_DETAIL not in", values, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailBetween(String value1, String value2) {
            addCriterion("EE_DETAIL between", value1, value2, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeDetailNotBetween(String value1, String value2) {
            addCriterion("EE_DETAIL not between", value1, value2, "eeDetail");
            return (Criteria) this;
        }

        public Criteria andEeCataIsNull() {
            addCriterion("EE_CATA is null");
            return (Criteria) this;
        }

        public Criteria andEeCataIsNotNull() {
            addCriterion("EE_CATA is not null");
            return (Criteria) this;
        }

        public Criteria andEeCataEqualTo(Integer value) {
            addCriterion("EE_CATA =", value, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataNotEqualTo(Integer value) {
            addCriterion("EE_CATA <>", value, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataGreaterThan(Integer value) {
            addCriterion("EE_CATA >", value, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataGreaterThanOrEqualTo(Integer value) {
            addCriterion("EE_CATA >=", value, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataLessThan(Integer value) {
            addCriterion("EE_CATA <", value, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataLessThanOrEqualTo(Integer value) {
            addCriterion("EE_CATA <=", value, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataIn(List<Integer> values) {
            addCriterion("EE_CATA in", values, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataNotIn(List<Integer> values) {
            addCriterion("EE_CATA not in", values, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataBetween(Integer value1, Integer value2) {
            addCriterion("EE_CATA between", value1, value2, "eeCata");
            return (Criteria) this;
        }

        public Criteria andEeCataNotBetween(Integer value1, Integer value2) {
            addCriterion("EE_CATA not between", value1, value2, "eeCata");
            return (Criteria) this;
        }

        public Criteria andOIdIsNull() {
            addCriterion("O_ID is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("O_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(Long value) {
            addCriterion("O_ID =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(Long value) {
            addCriterion("O_ID <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(Long value) {
            addCriterion("O_ID >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(Long value) {
            addCriterion("O_ID >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(Long value) {
            addCriterion("O_ID <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(Long value) {
            addCriterion("O_ID <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<Long> values) {
            addCriterion("O_ID in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<Long> values) {
            addCriterion("O_ID not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(Long value1, Long value2) {
            addCriterion("O_ID between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(Long value1, Long value2) {
            addCriterion("O_ID not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andUIdIsNull() {
            addCriterion("U_ID is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("U_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(Long value) {
            addCriterion("U_ID =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(Long value) {
            addCriterion("U_ID <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(Long value) {
            addCriterion("U_ID >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(Long value) {
            addCriterion("U_ID >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(Long value) {
            addCriterion("U_ID <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(Long value) {
            addCriterion("U_ID <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<Long> values) {
            addCriterion("U_ID in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<Long> values) {
            addCriterion("U_ID not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(Long value1, Long value2) {
            addCriterion("U_ID between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(Long value1, Long value2) {
            addCriterion("U_ID not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andEeTimeIsNull() {
            addCriterion("EE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andEeTimeIsNotNull() {
            addCriterion("EE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andEeTimeEqualTo(Date value) {
            addCriterion("EE_TIME =", value, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeNotEqualTo(Date value) {
            addCriterion("EE_TIME <>", value, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeGreaterThan(Date value) {
            addCriterion("EE_TIME >", value, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("EE_TIME >=", value, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeLessThan(Date value) {
            addCriterion("EE_TIME <", value, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeLessThanOrEqualTo(Date value) {
            addCriterion("EE_TIME <=", value, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeIn(List<Date> values) {
            addCriterion("EE_TIME in", values, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeNotIn(List<Date> values) {
            addCriterion("EE_TIME not in", values, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeBetween(Date value1, Date value2) {
            addCriterion("EE_TIME between", value1, value2, "eeTime");
            return (Criteria) this;
        }

        public Criteria andEeTimeNotBetween(Date value1, Date value2) {
            addCriterion("EE_TIME not between", value1, value2, "eeTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_expor_eva
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 20 16:51:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_expor_eva
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}