package com.shidao.web.model;

import java.util.ArrayList;
import java.util.List;

public class ExporExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public ExporExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEIdIsNull() {
            addCriterion("E_ID is null");
            return (Criteria) this;
        }

        public Criteria andEIdIsNotNull() {
            addCriterion("E_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEIdEqualTo(Long value) {
            addCriterion("E_ID =", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotEqualTo(Long value) {
            addCriterion("E_ID <>", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdGreaterThan(Long value) {
            addCriterion("E_ID >", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdGreaterThanOrEqualTo(Long value) {
            addCriterion("E_ID >=", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdLessThan(Long value) {
            addCriterion("E_ID <", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdLessThanOrEqualTo(Long value) {
            addCriterion("E_ID <=", value, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdIn(List<Long> values) {
            addCriterion("E_ID in", values, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotIn(List<Long> values) {
            addCriterion("E_ID not in", values, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdBetween(Long value1, Long value2) {
            addCriterion("E_ID between", value1, value2, "eId");
            return (Criteria) this;
        }

        public Criteria andEIdNotBetween(Long value1, Long value2) {
            addCriterion("E_ID not between", value1, value2, "eId");
            return (Criteria) this;
        }

        public Criteria andENameIsNull() {
            addCriterion("E_NAME is null");
            return (Criteria) this;
        }

        public Criteria andENameIsNotNull() {
            addCriterion("E_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andENameEqualTo(String value) {
            addCriterion("E_NAME =", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotEqualTo(String value) {
            addCriterion("E_NAME <>", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameGreaterThan(String value) {
            addCriterion("E_NAME >", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameGreaterThanOrEqualTo(String value) {
            addCriterion("E_NAME >=", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLessThan(String value) {
            addCriterion("E_NAME <", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLessThanOrEqualTo(String value) {
            addCriterion("E_NAME <=", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameLike(String value) {
            addCriterion("E_NAME like", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotLike(String value) {
            addCriterion("E_NAME not like", value, "eName");
            return (Criteria) this;
        }

        public Criteria andENameIn(List<String> values) {
            addCriterion("E_NAME in", values, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotIn(List<String> values) {
            addCriterion("E_NAME not in", values, "eName");
            return (Criteria) this;
        }

        public Criteria andENameBetween(String value1, String value2) {
            addCriterion("E_NAME between", value1, value2, "eName");
            return (Criteria) this;
        }

        public Criteria andENameNotBetween(String value1, String value2) {
            addCriterion("E_NAME not between", value1, value2, "eName");
            return (Criteria) this;
        }

        public Criteria andETelIsNull() {
            addCriterion("E_TEL is null");
            return (Criteria) this;
        }

        public Criteria andETelIsNotNull() {
            addCriterion("E_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andETelEqualTo(String value) {
            addCriterion("E_TEL =", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelNotEqualTo(String value) {
            addCriterion("E_TEL <>", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelGreaterThan(String value) {
            addCriterion("E_TEL >", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelGreaterThanOrEqualTo(String value) {
            addCriterion("E_TEL >=", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelLessThan(String value) {
            addCriterion("E_TEL <", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelLessThanOrEqualTo(String value) {
            addCriterion("E_TEL <=", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelLike(String value) {
            addCriterion("E_TEL like", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelNotLike(String value) {
            addCriterion("E_TEL not like", value, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelIn(List<String> values) {
            addCriterion("E_TEL in", values, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelNotIn(List<String> values) {
            addCriterion("E_TEL not in", values, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelBetween(String value1, String value2) {
            addCriterion("E_TEL between", value1, value2, "eTel");
            return (Criteria) this;
        }

        public Criteria andETelNotBetween(String value1, String value2) {
            addCriterion("E_TEL not between", value1, value2, "eTel");
            return (Criteria) this;
        }

        public Criteria andEIdnumIsNull() {
            addCriterion("E_IDNUM is null");
            return (Criteria) this;
        }

        public Criteria andEIdnumIsNotNull() {
            addCriterion("E_IDNUM is not null");
            return (Criteria) this;
        }

        public Criteria andEIdnumEqualTo(String value) {
            addCriterion("E_IDNUM =", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumNotEqualTo(String value) {
            addCriterion("E_IDNUM <>", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumGreaterThan(String value) {
            addCriterion("E_IDNUM >", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumGreaterThanOrEqualTo(String value) {
            addCriterion("E_IDNUM >=", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumLessThan(String value) {
            addCriterion("E_IDNUM <", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumLessThanOrEqualTo(String value) {
            addCriterion("E_IDNUM <=", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumLike(String value) {
            addCriterion("E_IDNUM like", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumNotLike(String value) {
            addCriterion("E_IDNUM not like", value, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumIn(List<String> values) {
            addCriterion("E_IDNUM in", values, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumNotIn(List<String> values) {
            addCriterion("E_IDNUM not in", values, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumBetween(String value1, String value2) {
            addCriterion("E_IDNUM between", value1, value2, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEIdnumNotBetween(String value1, String value2) {
            addCriterion("E_IDNUM not between", value1, value2, "eIdnum");
            return (Criteria) this;
        }

        public Criteria andEImgIsNull() {
            addCriterion("E_IMG is null");
            return (Criteria) this;
        }

        public Criteria andEImgIsNotNull() {
            addCriterion("E_IMG is not null");
            return (Criteria) this;
        }

        public Criteria andEImgEqualTo(String value) {
            addCriterion("E_IMG =", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgNotEqualTo(String value) {
            addCriterion("E_IMG <>", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgGreaterThan(String value) {
            addCriterion("E_IMG >", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgGreaterThanOrEqualTo(String value) {
            addCriterion("E_IMG >=", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgLessThan(String value) {
            addCriterion("E_IMG <", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgLessThanOrEqualTo(String value) {
            addCriterion("E_IMG <=", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgLike(String value) {
            addCriterion("E_IMG like", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgNotLike(String value) {
            addCriterion("E_IMG not like", value, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgIn(List<String> values) {
            addCriterion("E_IMG in", values, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgNotIn(List<String> values) {
            addCriterion("E_IMG not in", values, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgBetween(String value1, String value2) {
            addCriterion("E_IMG between", value1, value2, "eImg");
            return (Criteria) this;
        }

        public Criteria andEImgNotBetween(String value1, String value2) {
            addCriterion("E_IMG not between", value1, value2, "eImg");
            return (Criteria) this;
        }

        public Criteria andECardSrcIsNull() {
            addCriterion("E_CARD_SRC is null");
            return (Criteria) this;
        }

        public Criteria andECardSrcIsNotNull() {
            addCriterion("E_CARD_SRC is not null");
            return (Criteria) this;
        }

        public Criteria andECardSrcEqualTo(String value) {
            addCriterion("E_CARD_SRC =", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcNotEqualTo(String value) {
            addCriterion("E_CARD_SRC <>", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcGreaterThan(String value) {
            addCriterion("E_CARD_SRC >", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcGreaterThanOrEqualTo(String value) {
            addCriterion("E_CARD_SRC >=", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcLessThan(String value) {
            addCriterion("E_CARD_SRC <", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcLessThanOrEqualTo(String value) {
            addCriterion("E_CARD_SRC <=", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcLike(String value) {
            addCriterion("E_CARD_SRC like", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcNotLike(String value) {
            addCriterion("E_CARD_SRC not like", value, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcIn(List<String> values) {
            addCriterion("E_CARD_SRC in", values, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcNotIn(List<String> values) {
            addCriterion("E_CARD_SRC not in", values, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcBetween(String value1, String value2) {
            addCriterion("E_CARD_SRC between", value1, value2, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andECardSrcNotBetween(String value1, String value2) {
            addCriterion("E_CARD_SRC not between", value1, value2, "eCardSrc");
            return (Criteria) this;
        }

        public Criteria andEStateIsNull() {
            addCriterion("E_STATE is null");
            return (Criteria) this;
        }

        public Criteria andEStateIsNotNull() {
            addCriterion("E_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andEStateEqualTo(Integer value) {
            addCriterion("E_STATE =", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateNotEqualTo(Integer value) {
            addCriterion("E_STATE <>", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateGreaterThan(Integer value) {
            addCriterion("E_STATE >", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("E_STATE >=", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateLessThan(Integer value) {
            addCriterion("E_STATE <", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateLessThanOrEqualTo(Integer value) {
            addCriterion("E_STATE <=", value, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateIn(List<Integer> values) {
            addCriterion("E_STATE in", values, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateNotIn(List<Integer> values) {
            addCriterion("E_STATE not in", values, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateBetween(Integer value1, Integer value2) {
            addCriterion("E_STATE between", value1, value2, "eState");
            return (Criteria) this;
        }

        public Criteria andEStateNotBetween(Integer value1, Integer value2) {
            addCriterion("E_STATE not between", value1, value2, "eState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateIsNull() {
            addCriterion("E_VERY_STATE is null");
            return (Criteria) this;
        }

        public Criteria andEVeryStateIsNotNull() {
            addCriterion("E_VERY_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andEVeryStateEqualTo(Integer value) {
            addCriterion("E_VERY_STATE =", value, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateNotEqualTo(Integer value) {
            addCriterion("E_VERY_STATE <>", value, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateGreaterThan(Integer value) {
            addCriterion("E_VERY_STATE >", value, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("E_VERY_STATE >=", value, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateLessThan(Integer value) {
            addCriterion("E_VERY_STATE <", value, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateLessThanOrEqualTo(Integer value) {
            addCriterion("E_VERY_STATE <=", value, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateIn(List<Integer> values) {
            addCriterion("E_VERY_STATE in", values, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateNotIn(List<Integer> values) {
            addCriterion("E_VERY_STATE not in", values, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateBetween(Integer value1, Integer value2) {
            addCriterion("E_VERY_STATE between", value1, value2, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEVeryStateNotBetween(Integer value1, Integer value2) {
            addCriterion("E_VERY_STATE not between", value1, value2, "eVeryState");
            return (Criteria) this;
        }

        public Criteria andEAllratinIsNull() {
            addCriterion("E_ALLRATIN is null");
            return (Criteria) this;
        }

        public Criteria andEAllratinIsNotNull() {
            addCriterion("E_ALLRATIN is not null");
            return (Criteria) this;
        }

        public Criteria andEAllratinEqualTo(Double value) {
            addCriterion("E_ALLRATIN =", value, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinNotEqualTo(Double value) {
            addCriterion("E_ALLRATIN <>", value, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinGreaterThan(Double value) {
            addCriterion("E_ALLRATIN >", value, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinGreaterThanOrEqualTo(Double value) {
            addCriterion("E_ALLRATIN >=", value, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinLessThan(Double value) {
            addCriterion("E_ALLRATIN <", value, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinLessThanOrEqualTo(Double value) {
            addCriterion("E_ALLRATIN <=", value, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinIn(List<Double> values) {
            addCriterion("E_ALLRATIN in", values, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinNotIn(List<Double> values) {
            addCriterion("E_ALLRATIN not in", values, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinBetween(Double value1, Double value2) {
            addCriterion("E_ALLRATIN between", value1, value2, "eAllratin");
            return (Criteria) this;
        }

        public Criteria andEAllratinNotBetween(Double value1, Double value2) {
            addCriterion("E_ALLRATIN not between", value1, value2, "eAllratin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_expor
     *
     * @mbg.generated do_not_delete_during_merge Thu Mar 29 17:17:45 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_expor
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}