package com.shidao.web.model;

public class ExpUserRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exp_user_rel.ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exp_user_rel.EU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long euId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_exp_user_rel.E_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long eId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exp_user_rel.ID
     *
     * @return the value of t_exp_user_rel.ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exp_user_rel.ID
     *
     * @param id the value for t_exp_user_rel.ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exp_user_rel.EU_ID
     *
     * @return the value of t_exp_user_rel.EU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getEuId() {
        return euId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exp_user_rel.EU_ID
     *
     * @param euId the value for t_exp_user_rel.EU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setEuId(Long euId) {
        this.euId = euId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_exp_user_rel.E_ID
     *
     * @return the value of t_exp_user_rel.E_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_exp_user_rel.E_ID
     *
     * @param eId the value for t_exp_user_rel.E_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void seteId(Long eId) {
        this.eId = eId;
    }
}