package com.shidao.web.model;

import java.util.Date;

public class Food {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long fId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_NAME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private String fName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_DES
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private String fDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer fCata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_R_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long fRId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_PRICE_IN
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double fPriceIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_PRICE_OUT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double fPriceOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Date fTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_IMG
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private String fImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_ALLRATING
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double fAllrating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer fState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_DPRICE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double fDprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_ORDER_NUM
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer fOrderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.F_ORDER_MOT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer fOrderMot;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_ID
     *
     * @return the value of t_food.F_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_ID
     *
     * @param fId the value for t_food.F_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfId(Long fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_NAME
     *
     * @return the value of t_food.F_NAME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_NAME
     *
     * @param fName the value for t_food.F_NAME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfName(String fName) {
        this.fName = fName == null ? null : fName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_DES
     *
     * @return the value of t_food.F_DES
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public String getfDes() {
        return fDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_DES
     *
     * @param fDes the value for t_food.F_DES
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfDes(String fDes) {
        this.fDes = fDes == null ? null : fDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_CATA
     *
     * @return the value of t_food.F_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getfCata() {
        return fCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_CATA
     *
     * @param fCata the value for t_food.F_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfCata(Integer fCata) {
        this.fCata = fCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_R_ID
     *
     * @return the value of t_food.F_R_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getfRId() {
        return fRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_R_ID
     *
     * @param fRId the value for t_food.F_R_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfRId(Long fRId) {
        this.fRId = fRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_PRICE_IN
     *
     * @return the value of t_food.F_PRICE_IN
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getfPriceIn() {
        return fPriceIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_PRICE_IN
     *
     * @param fPriceIn the value for t_food.F_PRICE_IN
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfPriceIn(Double fPriceIn) {
        this.fPriceIn = fPriceIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_PRICE_OUT
     *
     * @return the value of t_food.F_PRICE_OUT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getfPriceOut() {
        return fPriceOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_PRICE_OUT
     *
     * @param fPriceOut the value for t_food.F_PRICE_OUT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfPriceOut(Double fPriceOut) {
        this.fPriceOut = fPriceOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_TIME
     *
     * @return the value of t_food.F_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Date getfTime() {
        return fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_TIME
     *
     * @param fTime the value for t_food.F_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfTime(Date fTime) {
        this.fTime = fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_IMG
     *
     * @return the value of t_food.F_IMG
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public String getfImg() {
        return fImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_IMG
     *
     * @param fImg the value for t_food.F_IMG
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfImg(String fImg) {
        this.fImg = fImg == null ? null : fImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_ALLRATING
     *
     * @return the value of t_food.F_ALLRATING
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getfAllrating() {
        return fAllrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_ALLRATING
     *
     * @param fAllrating the value for t_food.F_ALLRATING
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfAllrating(Double fAllrating) {
        this.fAllrating = fAllrating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_STATE
     *
     * @return the value of t_food.F_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getfState() {
        return fState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_STATE
     *
     * @param fState the value for t_food.F_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfState(Integer fState) {
        this.fState = fState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_DPRICE
     *
     * @return the value of t_food.F_DPRICE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getfDprice() {
        return fDprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_DPRICE
     *
     * @param fDprice the value for t_food.F_DPRICE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfDprice(Double fDprice) {
        this.fDprice = fDprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_ORDER_NUM
     *
     * @return the value of t_food.F_ORDER_NUM
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getfOrderNum() {
        return fOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_ORDER_NUM
     *
     * @param fOrderNum the value for t_food.F_ORDER_NUM
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfOrderNum(Integer fOrderNum) {
        this.fOrderNum = fOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.F_ORDER_MOT
     *
     * @return the value of t_food.F_ORDER_MOT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getfOrderMot() {
        return fOrderMot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.F_ORDER_MOT
     *
     * @param fOrderMot the value for t_food.F_ORDER_MOT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfOrderMot(Integer fOrderMot) {
        this.fOrderMot = fOrderMot;
    }
}