package com.shidao.web.model;

import java.util.Date;

public class FoodEva {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_eva.FE_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long feId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_eva.FE_DETAIL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String feDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_eva.FE_CATA
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Integer feCata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_eva.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_eva.U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food_eva.FE_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Date feTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_eva.FE_ID
     *
     * @return the value of t_food_eva.FE_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getFeId() {
        return feId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_eva.FE_ID
     *
     * @param feId the value for t_food_eva.FE_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setFeId(Long feId) {
        this.feId = feId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_eva.FE_DETAIL
     *
     * @return the value of t_food_eva.FE_DETAIL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getFeDetail() {
        return feDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_eva.FE_DETAIL
     *
     * @param feDetail the value for t_food_eva.FE_DETAIL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setFeDetail(String feDetail) {
        this.feDetail = feDetail == null ? null : feDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_eva.FE_CATA
     *
     * @return the value of t_food_eva.FE_CATA
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Integer getFeCata() {
        return feCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_eva.FE_CATA
     *
     * @param feCata the value for t_food_eva.FE_CATA
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setFeCata(Integer feCata) {
        this.feCata = feCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_eva.O_ID
     *
     * @return the value of t_food_eva.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_eva.O_ID
     *
     * @param oId the value for t_food_eva.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_eva.U_ID
     *
     * @return the value of t_food_eva.U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_eva.U_ID
     *
     * @param uId the value for t_food_eva.U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food_eva.FE_TIME
     *
     * @return the value of t_food_eva.FE_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Date getFeTime() {
        return feTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food_eva.FE_TIME
     *
     * @param feTime the value for t_food_eva.FE_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setFeTime(Date feTime) {
        this.feTime = feTime;
    }
}