package com.shidao.web.model;

public class OrderDetil {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detil.OD_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long odId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detil.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detil.F_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long fId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detil.OD_ID
     *
     * @return the value of t_order_detil.OD_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getOdId() {
        return odId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detil.OD_ID
     *
     * @param odId the value for t_order_detil.OD_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setOdId(Long odId) {
        this.odId = odId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detil.O_ID
     *
     * @return the value of t_order_detil.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detil.O_ID
     *
     * @param oId the value for t_order_detil.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detil.F_ID
     *
     * @return the value of t_order_detil.F_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detil.F_ID
     *
     * @param fId the value for t_order_detil.F_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setfId(Long fId) {
        this.fId = fId;
    }
}