package com.shidao.web.model;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long oUId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_R_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long oRId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_STATE
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Integer oState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_PAY_WAY
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Integer oPayWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_PAY_STATE
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Integer oPayState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Date oTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_ADDRESS
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String oAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_NAME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String oName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.O_TEL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String oTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_ID
     *
     * @return the value of t_order.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_ID
     *
     * @param oId the value for t_order.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_U_ID
     *
     * @return the value of t_order.O_U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getoUId() {
        return oUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_U_ID
     *
     * @param oUId the value for t_order.O_U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoUId(Long oUId) {
        this.oUId = oUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_R_ID
     *
     * @return the value of t_order.O_R_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getoRId() {
        return oRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_R_ID
     *
     * @param oRId the value for t_order.O_R_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoRId(Long oRId) {
        this.oRId = oRId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_STATE
     *
     * @return the value of t_order.O_STATE
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Integer getoState() {
        return oState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_STATE
     *
     * @param oState the value for t_order.O_STATE
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoState(Integer oState) {
        this.oState = oState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_PAY_WAY
     *
     * @return the value of t_order.O_PAY_WAY
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Integer getoPayWay() {
        return oPayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_PAY_WAY
     *
     * @param oPayWay the value for t_order.O_PAY_WAY
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoPayWay(Integer oPayWay) {
        this.oPayWay = oPayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_PAY_STATE
     *
     * @return the value of t_order.O_PAY_STATE
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Integer getoPayState() {
        return oPayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_PAY_STATE
     *
     * @param oPayState the value for t_order.O_PAY_STATE
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoPayState(Integer oPayState) {
        this.oPayState = oPayState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_TIME
     *
     * @return the value of t_order.O_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Date getoTime() {
        return oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_TIME
     *
     * @param oTime the value for t_order.O_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoTime(Date oTime) {
        this.oTime = oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_ADDRESS
     *
     * @return the value of t_order.O_ADDRESS
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getoAddress() {
        return oAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_ADDRESS
     *
     * @param oAddress the value for t_order.O_ADDRESS
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoAddress(String oAddress) {
        this.oAddress = oAddress == null ? null : oAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_NAME
     *
     * @return the value of t_order.O_NAME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getoName() {
        return oName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_NAME
     *
     * @param oName the value for t_order.O_NAME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoName(String oName) {
        this.oName = oName == null ? null : oName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.O_TEL
     *
     * @return the value of t_order.O_TEL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getoTel() {
        return oTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.O_TEL
     *
     * @param oTel the value for t_order.O_TEL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoTel(String oTel) {
        this.oTel = oTel == null ? null : oTel.trim();
    }
}