package com.shidao.web.model;

import java.util.Date;

public class ResEva {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_eva.RE_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long reId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_eva.RE_DETAIL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String reDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_eva.RE_CATA
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Integer reCata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_eva.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_eva.U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_eva.RE_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Date reTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_eva.RE_ID
     *
     * @return the value of t_res_eva.RE_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getReId() {
        return reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_eva.RE_ID
     *
     * @param reId the value for t_res_eva.RE_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setReId(Long reId) {
        this.reId = reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_eva.RE_DETAIL
     *
     * @return the value of t_res_eva.RE_DETAIL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getReDetail() {
        return reDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_eva.RE_DETAIL
     *
     * @param reDetail the value for t_res_eva.RE_DETAIL
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setReDetail(String reDetail) {
        this.reDetail = reDetail == null ? null : reDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_eva.RE_CATA
     *
     * @return the value of t_res_eva.RE_CATA
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Integer getReCata() {
        return reCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_eva.RE_CATA
     *
     * @param reCata the value for t_res_eva.RE_CATA
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setReCata(Integer reCata) {
        this.reCata = reCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_eva.O_ID
     *
     * @return the value of t_res_eva.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_eva.O_ID
     *
     * @param oId the value for t_res_eva.O_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_eva.U_ID
     *
     * @return the value of t_res_eva.U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_eva.U_ID
     *
     * @param uId the value for t_res_eva.U_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_eva.RE_TIME
     *
     * @return the value of t_res_eva.RE_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Date getReTime() {
        return reTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_eva.RE_TIME
     *
     * @param reTime the value for t_res_eva.RE_TIME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setReTime(Date reTime) {
        this.reTime = reTime;
    }
}