package com.shidao.web.model;

public class ResUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_user.RU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long ruId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_user.RU_LOGIN_NAME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String ruLoginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_user.RU_PASSWORD
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private String ruPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_user.RU_ID
     *
     * @return the value of t_res_user.RU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getRuId() {
        return ruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_user.RU_ID
     *
     * @param ruId the value for t_res_user.RU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setRuId(Long ruId) {
        this.ruId = ruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_user.RU_LOGIN_NAME
     *
     * @return the value of t_res_user.RU_LOGIN_NAME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getRuLoginName() {
        return ruLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_user.RU_LOGIN_NAME
     *
     * @param ruLoginName the value for t_res_user.RU_LOGIN_NAME
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setRuLoginName(String ruLoginName) {
        this.ruLoginName = ruLoginName == null ? null : ruLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_user.RU_PASSWORD
     *
     * @return the value of t_res_user.RU_PASSWORD
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getRuPassword() {
        return ruPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_user.RU_PASSWORD
     *
     * @param ruPassword the value for t_res_user.RU_PASSWORD
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setRuPassword(String ruPassword) {
        this.ruPassword = ruPassword == null ? null : ruPassword.trim();
    }
}