package com.shidao.web.model;

import java.util.ArrayList;
import java.util.List;

public class ResUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public ResUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRuIdIsNull() {
            addCriterion("RU_ID is null");
            return (Criteria) this;
        }

        public Criteria andRuIdIsNotNull() {
            addCriterion("RU_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRuIdEqualTo(Long value) {
            addCriterion("RU_ID =", value, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdNotEqualTo(Long value) {
            addCriterion("RU_ID <>", value, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdGreaterThan(Long value) {
            addCriterion("RU_ID >", value, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdGreaterThanOrEqualTo(Long value) {
            addCriterion("RU_ID >=", value, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdLessThan(Long value) {
            addCriterion("RU_ID <", value, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdLessThanOrEqualTo(Long value) {
            addCriterion("RU_ID <=", value, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdIn(List<Long> values) {
            addCriterion("RU_ID in", values, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdNotIn(List<Long> values) {
            addCriterion("RU_ID not in", values, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdBetween(Long value1, Long value2) {
            addCriterion("RU_ID between", value1, value2, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuIdNotBetween(Long value1, Long value2) {
            addCriterion("RU_ID not between", value1, value2, "ruId");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameIsNull() {
            addCriterion("RU_LOGIN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameIsNotNull() {
            addCriterion("RU_LOGIN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameEqualTo(String value) {
            addCriterion("RU_LOGIN_NAME =", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameNotEqualTo(String value) {
            addCriterion("RU_LOGIN_NAME <>", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameGreaterThan(String value) {
            addCriterion("RU_LOGIN_NAME >", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameGreaterThanOrEqualTo(String value) {
            addCriterion("RU_LOGIN_NAME >=", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameLessThan(String value) {
            addCriterion("RU_LOGIN_NAME <", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameLessThanOrEqualTo(String value) {
            addCriterion("RU_LOGIN_NAME <=", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameLike(String value) {
            addCriterion("RU_LOGIN_NAME like", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameNotLike(String value) {
            addCriterion("RU_LOGIN_NAME not like", value, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameIn(List<String> values) {
            addCriterion("RU_LOGIN_NAME in", values, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameNotIn(List<String> values) {
            addCriterion("RU_LOGIN_NAME not in", values, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameBetween(String value1, String value2) {
            addCriterion("RU_LOGIN_NAME between", value1, value2, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuLoginNameNotBetween(String value1, String value2) {
            addCriterion("RU_LOGIN_NAME not between", value1, value2, "ruLoginName");
            return (Criteria) this;
        }

        public Criteria andRuPasswordIsNull() {
            addCriterion("RU_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andRuPasswordIsNotNull() {
            addCriterion("RU_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andRuPasswordEqualTo(String value) {
            addCriterion("RU_PASSWORD =", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordNotEqualTo(String value) {
            addCriterion("RU_PASSWORD <>", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordGreaterThan(String value) {
            addCriterion("RU_PASSWORD >", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("RU_PASSWORD >=", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordLessThan(String value) {
            addCriterion("RU_PASSWORD <", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordLessThanOrEqualTo(String value) {
            addCriterion("RU_PASSWORD <=", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordLike(String value) {
            addCriterion("RU_PASSWORD like", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordNotLike(String value) {
            addCriterion("RU_PASSWORD not like", value, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordIn(List<String> values) {
            addCriterion("RU_PASSWORD in", values, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordNotIn(List<String> values) {
            addCriterion("RU_PASSWORD not in", values, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordBetween(String value1, String value2) {
            addCriterion("RU_PASSWORD between", value1, value2, "ruPassword");
            return (Criteria) this;
        }

        public Criteria andRuPasswordNotBetween(String value1, String value2) {
            addCriterion("RU_PASSWORD not between", value1, value2, "ruPassword");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_res_user
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 20 16:51:18 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}