package com.shidao.web.model;

public class ResUserRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_user_rel.ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_user_rel.RU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long ruId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_res_user_rel.R_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    private Long rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_user_rel.ID
     *
     * @return the value of t_res_user_rel.ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_user_rel.ID
     *
     * @param id the value for t_res_user_rel.ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_user_rel.RU_ID
     *
     * @return the value of t_res_user_rel.RU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getRuId() {
        return ruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_user_rel.RU_ID
     *
     * @param ruId the value for t_res_user_rel.RU_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setRuId(Long ruId) {
        this.ruId = ruId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_res_user_rel.R_ID
     *
     * @return the value of t_res_user_rel.R_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public Long getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_res_user_rel.R_ID
     *
     * @param rId the value for t_res_user_rel.R_ID
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    public void setrId(Long rId) {
        this.rId = rId;
    }
}