package com.shidao.web.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.id
     *
     * @mbg.generated Tue Mar 27 18:03:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testuser.name
     *
     * @mbg.generated Tue Mar 27 18:03:07 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.id
     *
     * @return the value of testuser.id
     *
     * @mbg.generated Tue Mar 27 18:03:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.id
     *
     * @param id the value for testuser.id
     *
     * @mbg.generated Tue Mar 27 18:03:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testuser.name
     *
     * @return the value of testuser.name
     *
     * @mbg.generated Tue Mar 27 18:03:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testuser.name
     *
     * @param name the value for testuser.name
     *
     * @mbg.generated Tue Mar 27 18:03:07 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}