package com.shidao.web.model;

public class UserAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.ID
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.U_ID
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.UA_AREA
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    private Integer uaArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.UA_DETAIL
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    private String uaDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.U_PHONE
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    private String uPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_address.U_NAME
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    private String uName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.ID
     *
     * @return the value of t_user_address.ID
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.ID
     *
     * @param id the value for t_user_address.ID
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.U_ID
     *
     * @return the value of t_user_address.U_ID
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.U_ID
     *
     * @param uId the value for t_user_address.U_ID
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.UA_AREA
     *
     * @return the value of t_user_address.UA_AREA
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public Integer getUaArea() {
        return uaArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.UA_AREA
     *
     * @param uaArea the value for t_user_address.UA_AREA
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public void setUaArea(Integer uaArea) {
        this.uaArea = uaArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.UA_DETAIL
     *
     * @return the value of t_user_address.UA_DETAIL
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public String getUaDetail() {
        return uaDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.UA_DETAIL
     *
     * @param uaDetail the value for t_user_address.UA_DETAIL
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public void setUaDetail(String uaDetail) {
        this.uaDetail = uaDetail == null ? null : uaDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.U_PHONE
     *
     * @return the value of t_user_address.U_PHONE
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public String getuPhone() {
        return uPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.U_PHONE
     *
     * @param uPhone the value for t_user_address.U_PHONE
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public void setuPhone(String uPhone) {
        this.uPhone = uPhone == null ? null : uPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_address.U_NAME
     *
     * @return the value of t_user_address.U_NAME
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_address.U_NAME
     *
     * @param uName the value for t_user_address.U_NAME
     *
     * @mbg.generated Fri May 25 15:27:26 CST 2018
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }
}