package com.shidao.web.model;

public class UserCoupon {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.UC_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long ucId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.U_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.C_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_coupon.UC_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer ucState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.UC_ID
     *
     * @return the value of t_user_coupon.UC_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getUcId() {
        return ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.UC_ID
     *
     * @param ucId the value for t_user_coupon.UC_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setUcId(Long ucId) {
        this.ucId = ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.U_ID
     *
     * @return the value of t_user_coupon.U_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.U_ID
     *
     * @param uId the value for t_user_coupon.U_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.C_ID
     *
     * @return the value of t_user_coupon.C_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.C_ID
     *
     * @param cId the value for t_user_coupon.C_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_coupon.UC_STATE
     *
     * @return the value of t_user_coupon.UC_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getUcState() {
        return ucState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_coupon.UC_STATE
     *
     * @param ucState the value for t_user_coupon.UC_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setUcState(Integer ucState) {
        this.ucState = ucState;
    }
}