package com.shidao.web.vo;

import java.util.Date;

public class CouponVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer cCata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_TOTAL
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer cTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_SUB
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer cSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_DPR
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double cDpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_NUM
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer cNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_STARTTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Date cStarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon.C_ENDTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Date cEndtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_ID
     *
     * @return the value of t_coupon.C_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_ID
     *
     * @param cId the value for t_coupon.C_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_CATA
     *
     * @return the value of t_coupon.C_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getcCata() {
        return cCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_CATA
     *
     * @param cCata the value for t_coupon.C_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcCata(Integer cCata) {
        this.cCata = cCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_TOTAL
     *
     * @return the value of t_coupon.C_TOTAL
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getcTotal() {
        return cTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_TOTAL
     *
     * @param cTotal the value for t_coupon.C_TOTAL
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcTotal(Integer cTotal) {
        this.cTotal = cTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_SUB
     *
     * @return the value of t_coupon.C_SUB
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getcSub() {
        return cSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_SUB
     *
     * @param cSub the value for t_coupon.C_SUB
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcSub(Integer cSub) {
        this.cSub = cSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_DPR
     *
     * @return the value of t_coupon.C_DPR
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getcDpr() {
        return cDpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_DPR
     *
     * @param cDpr the value for t_coupon.C_DPR
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcDpr(Double cDpr) {
        this.cDpr = cDpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_NUM
     *
     * @return the value of t_coupon.C_NUM
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getcNum() {
        return cNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_NUM
     *
     * @param cNum the value for t_coupon.C_NUM
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcNum(Integer cNum) {
        this.cNum = cNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_STARTTIME
     *
     * @return the value of t_coupon.C_STARTTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Date getcStarttime() {
        return cStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_STARTTIME
     *
     * @param cStarttime the value for t_coupon.C_STARTTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcStarttime(Date cStarttime) {
        this.cStarttime = cStarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon.C_ENDTIME
     *
     * @return the value of t_coupon.C_ENDTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Date getcEndtime() {
        return cEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon.C_ENDTIME
     *
     * @param cEndtime the value for t_coupon.C_ENDTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setcEndtime(Date cEndtime) {
        this.cEndtime = cEndtime;
    }
}