package com.shidao.web.vo;

public class DictTypeVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_type.DT_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer dtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dict_type.DT_NAME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private String dtName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_type.DT_ID
     *
     * @return the value of t_dict_type.DT_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getDtId() {
        return dtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_type.DT_ID
     *
     * @param dtId the value for t_dict_type.DT_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setDtId(Integer dtId) {
        this.dtId = dtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dict_type.DT_NAME
     *
     * @return the value of t_dict_type.DT_NAME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public String getDtName() {
        return dtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dict_type.DT_NAME
     *
     * @param dtName the value for t_dict_type.DT_NAME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setDtName(String dtName) {
        this.dtName = dtName == null ? null : dtName.trim();
    }
}