package com.shidao.web.vo;

import java.util.Date;

public class ExporEvaVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expor_eva.EE_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long eeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expor_eva.EE_DETAIL
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private String eeDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expor_eva.EE_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer eeCata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expor_eva.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expor_eva.U_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expor_eva.EE_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Date eeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expor_eva.EE_ID
     *
     * @return the value of t_expor_eva.EE_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getEeId() {
        return eeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expor_eva.EE_ID
     *
     * @param eeId the value for t_expor_eva.EE_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setEeId(Long eeId) {
        this.eeId = eeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expor_eva.EE_DETAIL
     *
     * @return the value of t_expor_eva.EE_DETAIL
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public String getEeDetail() {
        return eeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expor_eva.EE_DETAIL
     *
     * @param eeDetail the value for t_expor_eva.EE_DETAIL
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setEeDetail(String eeDetail) {
        this.eeDetail = eeDetail == null ? null : eeDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expor_eva.EE_CATA
     *
     * @return the value of t_expor_eva.EE_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getEeCata() {
        return eeCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expor_eva.EE_CATA
     *
     * @param eeCata the value for t_expor_eva.EE_CATA
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setEeCata(Integer eeCata) {
        this.eeCata = eeCata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expor_eva.O_ID
     *
     * @return the value of t_expor_eva.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expor_eva.O_ID
     *
     * @param oId the value for t_expor_eva.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expor_eva.U_ID
     *
     * @return the value of t_expor_eva.U_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expor_eva.U_ID
     *
     * @param uId the value for t_expor_eva.U_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expor_eva.EE_TIME
     *
     * @return the value of t_expor_eva.EE_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Date getEeTime() {
        return eeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expor_eva.EE_TIME
     *
     * @param eeTime the value for t_expor_eva.EE_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setEeTime(Date eeTime) {
        this.eeTime = eeTime;
    }
}