package com.shidao.web.vo;

import java.util.Date;

public class OrderDispatchVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.D_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.E_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Long eId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.D_LON
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double dLon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.D_LAT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Double dLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.D_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Integer dState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.D_PERTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Date dPertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_dispatch.D_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    private Date dTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.D_ID
     *
     * @return the value of t_order_dispatch.D_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.D_ID
     *
     * @param dId the value for t_order_dispatch.D_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setdId(Long dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.O_ID
     *
     * @return the value of t_order_dispatch.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.O_ID
     *
     * @param oId the value for t_order_dispatch.O_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setoId(Long oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.E_ID
     *
     * @return the value of t_order_dispatch.E_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Long geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.E_ID
     *
     * @param eId the value for t_order_dispatch.E_ID
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void seteId(Long eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.D_LON
     *
     * @return the value of t_order_dispatch.D_LON
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getdLon() {
        return dLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.D_LON
     *
     * @param dLon the value for t_order_dispatch.D_LON
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setdLon(Double dLon) {
        this.dLon = dLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.D_LAT
     *
     * @return the value of t_order_dispatch.D_LAT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Double getdLat() {
        return dLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.D_LAT
     *
     * @param dLat the value for t_order_dispatch.D_LAT
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setdLat(Double dLat) {
        this.dLat = dLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.D_STATE
     *
     * @return the value of t_order_dispatch.D_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Integer getdState() {
        return dState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.D_STATE
     *
     * @param dState the value for t_order_dispatch.D_STATE
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setdState(Integer dState) {
        this.dState = dState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.D_PERTIME
     *
     * @return the value of t_order_dispatch.D_PERTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Date getdPertime() {
        return dPertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.D_PERTIME
     *
     * @param dPertime the value for t_order_dispatch.D_PERTIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setdPertime(Date dPertime) {
        this.dPertime = dPertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_dispatch.D_TIME
     *
     * @return the value of t_order_dispatch.D_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public Date getdTime() {
        return dTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_dispatch.D_TIME
     *
     * @param dTime the value for t_order_dispatch.D_TIME
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    public void setdTime(Date dTime) {
        this.dTime = dTime;
    }
}