create database EAT_PHIL_DEBUG;
use EAT_PHIL_DEBUG;
create table T_DICT_TYPE(
	DT_ID INT PRIMARY KEY,
	DT_NAME VARCHAR(50)
)charset utf8;
create table T_DICT_ITEM(
	DI_ID INT PRIMARY KEY,
	DT_ID INT,
	DI_NAME VARCHAR(50),
	DI_UPDTID INT,
	DI_EFFECTIVE TINYINT(1)
)charset utf8;
create table T_USER(
	U_ID BIGINT(20) PRIMARY KEY,
	U_LOGIN_NAME VARCHAR(30) UNIQUE,
	U_NICK_NAME VARCHAR(30),
	U_PASSWORD  VARCHAR(30) NOT NULL,
	U_SEX CHAR(1) NOT NULL,
	U_BIRTHDAY DATE,
	U_NAME VARCHAR(30),
	U_EMAIL VARCHAR(100),
	U_HEADPORTRAIT VARCHAR(100),
	U_AGE INT NOT NULL,
	U_TIME DATETIME NOT NULL,
	U_LON DOUBLE,
	U_LAT DOUBLE,
	U_RANK INT,
	U_SCORE INT,
	U_LOGIN_IP VARCHAR(30),
	U_ACTIVATE_CODE VARCHAR(6)
	
)charset utf8;
create table T_RESTAURANT(
	R_ID BIGINT(20) PRIMARY KEY,
	R_NAME VARCHAR(100) UNIQUE NOT NULL,
	R_PROVINCE INT,
	R_CITY INT,
	R_AREA INT,
	R_ADDRESS VARCHAR(100) NOT NULL,
	R_LON DOUBLE NOT NULL,
	R_LAT DOUBLE NOT NULL,
	R_TEL VARCHAR(11) NOT NULL, 
	R_ALLRATING DOUBLE NOT NULL,
	R_STATE INT,
	R_WORK_TIME DATE,
	R_ORDER_NUM INT,
	R_ORDER_MOT INT
)charset utf8;
create table T_FOOD (
	F_ID BIGINT(20) PRIMARY KEY,
	F_NAME VARCHAR(100) NOT NULL,
	F_DES VARCHAR(150) NOT NULL,
	F_CATA INT NOT NULL,
	F_R_ID BIGINT(20),
	F_PRICE_IN DOUBLE NOT NULL,
	F_PRICE_OUT DOUBLE NOT NULL,
	F_TIME DATE NOT NULL,
	F_IMG VARCHAR(100),
	F_ALLRATING DOUBLE NOT NULL,
	F_STATE INT,
	F_DPRICE DOUBLE NOT NULL,
	F_ORDER_NUM INT,
	F_ORDER_MOT INT
)charset utf8;
create table T_ORDER (
	O_ID BIGINT(20) PRIMARY KEY,
	O_U_ID BIGINT(20),
	O_R_ID BIGINT(20),
	O_STATE INT,
	O_PAY_WAY INT,
	O_PAY_STATE INT,
	O_TIME DATETIME NOT NULL,
	O_ADDRESS VARCHAR(100) NOT NULL,
	O_NAME VARCHAR(50) NOT NULL,
	O_TEL VARCHAR(11)
)charset utf8;
create table T_ORDER_DETIL(
	OD_ID BIGINT(20) PRIMARY KEY,
	O_ID BIGINT(20),
	F_ID BIGINT(20)
)charset utf8;
create table T_EXPOR(
	E_ID BIGINT(20) PRIMARY KEY,
	E_NAME VARCHAR(100) NOT NULL,
	E_TEL VARCHAR(11) NOT NULL,
	E_IDNUM VARCHAR(18) NOT NULL,
	E_IMG VARCHAR(100),
	E_CARD_SRC VARCHAR(100) NOT NULL,
	E_STATE INT,
	E_VERY_STATE INT,
	E_ALLRATIN DOUBLE NOT NULL
)charset utf8;
create table T_ORDER_DISPATCH(
	D_ID BIGINT(20) PRIMARY KEY,
	O_ID BIGINT(20),
	E_ID BIGINT(20),
	D_LON DOUBLE,
	D_LAT DOUBLE,
	D_STATE INT,
	D_PERTIME DATETIME,
	D_TIME DATETIME
)charset utf8;
create table T_RES_EVA(
	RE_ID BIGINT(20) PRIMARY KEY,
	RE_DETAIL VARCHAR(200) NOT NULL,
	RE_CATA INT,
	O_ID BIGINT(20),
	U_ID BIGINT(20),
	RE_TIME DATETIME NOT NULL
)charset utf8;
create table T_FOOD_EVA(
	FE_ID BIGINT(20) PRIMARY KEY,
	FE_DETAIL VARCHAR(200) NOT NULL,
	FE_CATA INT,
	O_ID BIGINT(20),
	U_ID BIGINT(20),
	FE_TIME DATETIME NOT NULL
)charset utf8;
create table T_EXPOR_EVA(
	EE_ID BIGINT(20) PRIMARY KEY,
	EE_DETAIL VARCHAR(200) NOT NULL,
	EE_CATA INT,
	O_ID BIGINT(20),
	U_ID BIGINT(20),
	EE_TIME DATETIME NOT NULL
)charset utf8;
create table T_COUPON(
	C_ID BIGINT(20) PRIMARY KEY,
	C_CATA INT,
	C_TOTAL INT,
	C_SUB INT,
	C_DPR DOUBLE,
	C_NUM INT NOT NULL,
	C_STARTTIME DATETIME,
	C_ENDTIME DATETIME
)charset utf8;
create table T_USER_COUPON(
	UC_ID BIGINT(20) PRIMARY KEY,
	U_ID BIGINT(20),
	C_ID BIGINT(20),
	UC_STATE INT
)charset utf8;
create table T_BACK_USER(
	BU_ID BIGINT(20) PRIMARY KEY,
	BU_LOGIN_NAME VARCHAR(100) NOT NULL,
	BU_PASSWORD VARCHAR(30) NOT NULL
)charset utf8;
create table T_RES_USER(
	RU_ID BIGINT(20) PRIMARY KEY,
	RU_LOGIN_NAME VARCHAR(11) NOT NULL,
	RU_PASSWORD VARCHAR(30) NOT NULL
)charset utf8;
create table T_EXP_USER(
	EU_ID BIGINT(20) PRIMARY KEY,
	EU_LOGIN_NAME VARCHAR(11) NOT NULL,
	EU_PASSWORD VARCHAR(30) NOT NULL
)charset utf8;
create table T_RES_USER_REL(
	ID BIGINT(20) PRIMARY KEY,
	RU_ID BIGINT(20),
	R_ID BIGINT(20)
)charset utf8;
create table T_EXP_USER_REL(
	ID BIGINT(20) PRIMARY KEY,
	EU_ID BIGINT(20),
	E_ID BIGINT(20)
)charset utf8;
create table T_USER_ADDRESS(
	ID BIGINT(20) PRIMARY KEY,
	U_ID BIGINT(20),
	UA_AREA INT,
	UA_DETAIL VARCHAR(100)
)charset utf8;
