package com.shidao.web.dao;

import com.shidao.web.model.Coupon;
import com.shidao.web.model.CouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    long countByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    List<Coupon> selectByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    Coupon selectByPrimaryKey(Long cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExample(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKey(Coupon record);
}