package com.shidao.web.dao;

import com.shidao.web.model.DictType;
import com.shidao.web.model.DictTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    long countByExample(DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByExample(DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByPrimaryKey(Integer dtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insert(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insertSelective(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    List<DictType> selectByExample(DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    DictType selectByPrimaryKey(Integer dtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictType record, @Param("example") DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExample(@Param("record") DictType record, @Param("example") DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_type
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKey(DictType record);
}