package com.shidao.web.dao;

import com.shidao.web.model.DictItem;
import com.shidao.web.model.DictItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    long countByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByPrimaryKey(Integer diId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insert(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insertSelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    List<DictItem> selectByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    DictItem selectByPrimaryKey(Integer diId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") DictItem record, @Param("example") DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExample(@Param("record") DictItem record, @Param("example") DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict_item
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKey(DictItem record);
}