package com.shidao.web.dao;

import com.shidao.web.model.OrderDetil;
import com.shidao.web.model.OrderDetilExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    long countByExample(OrderDetilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int deleteByExample(OrderDetilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int deleteByPrimaryKey(Long odId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int insert(OrderDetil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int insertSelective(OrderDetil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    List<OrderDetil> selectByExample(OrderDetilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    OrderDetil selectByPrimaryKey(Long odId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderDetil record, @Param("example") OrderDetilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByExample(@Param("record") OrderDetil record, @Param("example") OrderDetilExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByPrimaryKeySelective(OrderDetil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detil
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByPrimaryKey(OrderDetil record);
}