package com.shidao.web.dao;

import com.shidao.web.model.OrderDispatch;
import com.shidao.web.model.OrderDispatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDispatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    long countByExample(OrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByExample(OrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByPrimaryKey(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insert(OrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insertSelective(OrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    List<OrderDispatch> selectByExample(OrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    OrderDispatch selectByPrimaryKey(Long dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrderDispatch record, @Param("example") OrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExample(@Param("record") OrderDispatch record, @Param("example") OrderDispatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(OrderDispatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_dispatch
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKey(OrderDispatch record);
}