package com.shidao.web.dao;

import com.shidao.web.model.Restaurant;
import com.shidao.web.model.RestaurantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    long countByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByPrimaryKey(Long rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insert(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insertSelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    List<Restaurant> selectByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    Restaurant selectByPrimaryKey(Long rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") Restaurant record, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExample(@Param("record") Restaurant record, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(Restaurant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_restaurant
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKey(Restaurant record);
}