package com.shidao.web.dao;

import com.shidao.web.model.ResUserRel;
import com.shidao.web.model.ResUserRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    long countByExample(ResUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int deleteByExample(ResUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int insert(ResUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int insertSelective(ResUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    List<ResUserRel> selectByExample(ResUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    ResUserRel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResUserRel record, @Param("example") ResUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByExample(@Param("record") ResUserRel record, @Param("example") ResUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByPrimaryKeySelective(ResUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user_rel
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByPrimaryKey(ResUserRel record);
}