package com.shidao.web.dao;

import com.shidao.web.model.ResUser;
import com.shidao.web.model.ResUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    long countByExample(ResUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int deleteByExample(ResUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int deleteByPrimaryKey(Long ruId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int insert(ResUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int insertSelective(ResUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    List<ResUser> selectByExample(ResUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    ResUser selectByPrimaryKey(Long ruId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResUser record, @Param("example") ResUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByExample(@Param("record") ResUser record, @Param("example") ResUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByPrimaryKeySelective(ResUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_res_user
     *
     * @mbg.generated Fri Apr 20 16:51:18 CST 2018
     */
    int updateByPrimaryKey(ResUser record);
}