package com.shidao.web.dao;

import com.shidao.web.model.UserCoupon;
import com.shidao.web.model.UserCouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    long countByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int deleteByPrimaryKey(Long ucId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    List<UserCoupon> selectByExample(UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    UserCoupon selectByPrimaryKey(Long ucId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByExample(@Param("record") UserCoupon record, @Param("example") UserCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_coupon
     *
     * @mbg.generated Thu Mar 29 17:17:45 CST 2018
     */
    int updateByPrimaryKey(UserCoupon record);
}